/// Flutter icons YumziApp
/// Copyright (C) 2026 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  AllergenIcons
///      fonts:
///       - asset: fonts/AllergenIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class YumziAllergenIcons {
  YumziAllergenIcons._();

  static const _kFontFam = 'AllergenIcons';
  static const String? _kFontPkg = null;

  static const IconData wheat = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData walnut = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lupine = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sulfur_dioxide___sulphites = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData soya = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData soy_bean = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shrimp = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sesame = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData squid = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData potato = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pork = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData orange = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData nuts = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mushroom = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData milk = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData matsuke = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData peach = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData kiwi = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gluten = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gelatin = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fish = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData eggs = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData crab = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chicken = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData celery = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cashew = IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData beef = IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData banana = IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData apple = IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData abalone = IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
